version: '3.8'
services:
  backend:
    image: spring-boot-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - CORS_ALLOWED_ORIGINS=*
    restart: always
